import type {
  Row, Pillar, Framework, Why, Faq, Service, Module, Testimonial, Plan, Audience, Format, Article,
} from "./content";

// The full site copy in both languages. `en` is the source of truth; `he` is
// typed as `Dict`, so the compiler flags any key that drifts out of sync.

const en = {
  ui: {
    langName: "English",
    otherLangName: "עברית",
    otherLangShort: "עב",
    nav: { home: "Home", advisory: "Advisory & Mediation", training: "Training", insights: "Insights" },
    tabs: { home: "Home", advisory: "Advisory", training: "Training", book: "Book", client: "Client" },
    share: { aria: "Share LALUM", copied: "Link copied", text: "LALUM, Tech-Legal and Strategic Advisory" },
    whatsapp: { aria: "Chat with us on WhatsApp", msg: "Hello, I came from the LALUM app and would like to talk." },
    consent: {
      pre: "I agree to receive marketing material and updates from LALUM by WhatsApp, email, SMS, phone, and similar, and I accept the ",
      terms: "Terms",
      mid: " and ",
      privacy: "Privacy Policy",
      post: ". You can opt out at any time.",
    },
    guide: {
      open: "Guide",
      title: "Quick start guide",
      intro: "Everything you can do here, in five steps. One place, from your phone or computer.",
      close: "Close",
      steps: [
        { title: "Enter your client area", body: "Register once with an email and password, then simply sign in each time.", cta: "Sign in" },
        { title: "Message the firm", body: "Pick a topic, write, and send. We reply by email and in your thread.", cta: "Open client area" },
        { title: "Send a document", body: "Upload files securely (PDF, images, office documents, up to 25 MB). We are notified at once.", cta: "Open client area" },
        { title: "Book a meeting", body: "Choose a day and time, add a short note, and we confirm within one business hour.", cta: "Book a meeting" },
        { title: "Ask LEX", body: "Ask our AI assistant a general question, or attach a contract for review notes.", cta: "Open chat" },
      ],
      moreTitle: "More",
      qa: "Q&A",
      articles: "Articles",
      download: "Install the app",
      aiNote: "LEX is an AI tool. Its answers are not legal advice and do not replace review by a licensed attorney.",
    },
    clientLogin: "Client login",
    clientPortal: "Client portal",
    seeWhatWeDo: "See what we do →",
    initiateRisk: "Initiate a risk assessment",
    skipToContent: "Skip to content",
    footerLinks: { home: "Home", advisory: "Advisory & Mediation", training: "Training", insights: "Insights", login: "Client login", terms: "Terms", privacy: "Privacy", accessibility: "Accessibility", security: "Security", cookies: "Cookie settings", qa: "Q&A", articles: "Articles" },
    footer: { explore: "Explore", client: "Client", contact: "Contact", book: "Book a call", city: "Herzliya", tagline: "Tech-Legal and strategic counsel for startups and breakthrough companies.", rights: "All rights reserved.", downloadTitle: "Download the app and start working, fast and professional.", downloadSub: "Scan the QR code with your phone camera to install the app.", qrAlt: "QR code to open lalumapp.com", follow: "Follow LALUM", linkedin: "LALUM on LinkedIn", facebook: "LALUM on Facebook", instagram: "LALUM on Instagram", website: "Firm website" },
    cookie: { title: "Cookie settings", intro: "We use only what's needed to run this site. Essential cookies keep the app working; analytics are optional and off unless you allow them.", essential: "Essential", essentialNote: "Always on. Required for the site to function (session, security, preferences).", analytics: "Analytics", analyticsNote: "Anonymous usage statistics to help us improve. Off by default.", accept: "Accept all", reject: "Reject non-essential", save: "Save choices", saved: "Your cookie choices were saved.", banner: "We use essential cookies to run the site, and optional analytics only with your consent.", manage: "Manage" },
    a11y: { open: "Accessibility menu", title: "Accessibility", textSize: "Text size", contrast: "High contrast", links: "Highlight links", readable: "Readable font", motion: "Reduce motion", reset: "Reset", statement: "Accessibility statement" },
    chat: {
      title: "LEX · LALUM",
      subtitle: "General legal info, not legal advice",
      greeting: "Hi, I'm LEX, LALUM's legal AI assistant. Ask a general legal question, or attach a contract and I'll share remarks. On startups, IP, AI regulation, contracts, or mediation.",
      placeholder: "Ask a legal question…",
      send: "Send message",
      open: "Chat with the LALUM assistant",
      thinking: "Thinking…",
      demoReply: "This is a demo build, so the live assistant is not connected here. For a specific question, book a call and we'll respond within one business hour. This is general information, not legal advice.",
      errorReply: "Something went wrong reaching the assistant. Please try again in a moment, or book a call with us.",
      attach: "Upload a contract for review and remarks",
      attaching: "Reading the file…",
      attached: "Attached",
      remove: "Remove",
      fileErr: "Could not read the file. Please try a PDF or DOCX.",
      reviewPrefix: "Attached contract for review",
      reviewAsk: "Please review this contract and share your remarks.",
      disclaimer: "* This system is AI-based. The information and remarks produced by the bot are not legal advice, and neither the firm nor anyone on its behalf bears any liability for damage, direct or indirect, including the consequences of using this information. The firm's sole and full responsibility applies only to individual written legal advice provided against orderly payment.",
    },
    login: {
      eyebrow: "Client area",
      signIn: "Sign in",
      createAccount: "Create an account",
      subtitle: "Access your messages, documents, bookings, and payments.",
      demo: "Demo mode: no Supabase connection is configured, so any email and a 6+ character password will sign you in locally.",
      confirmEmail: "Check your inbox to confirm your email, then sign in.",
      email: "Email",
      password: "Password",
      emailPlaceholder: "you@company.com",
      passwordPlaceholder: "At least 6 characters",
      pleaseWait: "Please wait…",
      newHere: "New to LALUM? ",
      haveAccount: "Already have an account? ",
    },
    portal: {
      eyebrow: "Client portal",
      welcome: "Welcome back",
      signOut: "Sign out",
      demo: "Demo mode: Supabase is not configured, so submissions below are simulated locally and not sent anywhere. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to connect the live backend.",
      book: {
        title: "Book a diagnostics session",
        step1: "1 · Choose a day",
        step2: "2 · Choose a time",
        step3: "3 · What's it about? (optional)",
        topicPlaceholder: "Briefly, the matter you'd like to map.",
        submit: "Request this slot",
        sending: "Sending…",
        okPrefix: "Request received for",
        okAt: "at",
        okSuffix: "We'll confirm within one business hour.",
        err: "We couldn't send the request. Please try again.",
      },
      messages: {
        title: "Message the firm",
        intro: "Send us a secure message. Every inquiry is handled through the firm's customer service system, and we reply by email.",
        category: "Topic",
        categories: { general: "General inquiry", booking: "Meeting / scheduling", documents: "Documents", billing: "Billing" },
        subject: "Subject (optional)",
        subjectPlaceholder: "A short headline",
        body: "Message",
        bodyPlaceholder: "How can we help?",
        submit: "Send message",
        sending: "Sending…",
        ok: "Message sent. We'll reply to your email shortly.",
        err: "The message could not be sent. Please try again.",
        note: "Office, phone and Zoom meetings in Herzliya can be scheduled directly. Meetings outside the office are arranged with the firm in advance.",
      },
      files: {
        title: "Share documents",
        intro: "Upload documents securely. Only you and the firm can access them. We're notified as soon as a file arrives.",
        choose: "Choose a file",
        uploading: "Uploading…",
        ok: "File shared. The firm has been notified.",
        err: "The upload failed. Please try again.",
        tooBig: "This file is over the 25 MB limit.",
        yourFiles: "Your files",
        none: "No files shared yet.",
        download: "Download",
        remove: "Remove",
        confirmRemove: "Remove this file?",
        hint: "Up to 25 MB per file. PDF, images, and office documents are supported.",
      },
      thread: {
        title: "Your conversation",
        awaiting: "Awaiting a reply from the firm.",
        replyLabel: "Reply from LALUM",
      },
      inbox: {
        title: "Client inbox",
        intro: "Every client message. Draft a reply with AI, edit it, and approve to send.",
        none: "No client messages yet.",
        from: "From",
        draftAi: "Draft with AI",
        drafting: "Drafting…",
        replyPlaceholder: "Write or edit the reply, then approve to send…",
        send: "Approve & send",
        sending: "Sending…",
        replied: "Replied",
        newBadge: "New",
      },
      billing: {
        title: "Payments",
        intro: "Your billing milestones. Pay securely with Bit, Apple Pay, Google Pay, or card.",
        none: "No payments due right now.",
        pay: "Pay now",
        paying: "Opening secure checkout…",
        amount: "Amount",
        statusLabels: { pending: "Awaiting payment", sent: "Awaiting payment", paid: "Paid", failed: "Payment failed" },
        payErr: "Could not open checkout. Please try again.",
        adminTitle: "Billing",
        adminIntro: "Create a payment milestone for a client. They can pay it from their portal.",
        clientEmail: "Client email",
        clientEmailPh: "client@company.com",
        itemTitle: "What is this for?",
        itemTitlePh: "Retainer, milestone, consultation",
        amountPh: "0.00",
        create: "Create milestone",
        creating: "Creating…",
        createdOk: "Milestone created.",
        err: "Something went wrong. Please try again.",
        allTitle: "All milestones",
        copyLink: "Copy pay link",
        copied: "Copied",
      },
    },
    article: {
      allArticles: "All articles",
      by: "By Dr. Avraham Lalum",
      seal: "Attorney & Notary · Ph.D. in Law & Economics · Head of AI, Lalum.",
      keepReading: "Keep reading",
      keepReadingHead: "Bring the same rigor to your own matters.",
    },
    bookPage: {
      navCta: "Book a call",
      eyebrow: "Book a meeting",
      title: "Schedule a Tech-Legal Diagnostics session",
      subtitle: "Pick a slot that works for you. No account needed. We map your architecture, structure, and regulatory exposure, and return a tailored roadmap.",
      subtitleLive: "Choose a time below. You'll get an instant email confirmation and a calendar invite, and the meeting is added to our calendar automatically.",
      step1: "1 · Choose a day",
      step2: "2 · Choose a time",
      name: "Full name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "you@company.com",
      topic: "3 · What's it about? (optional)",
      topicPlaceholder: "Briefly, the matter you'd like to map.",
      submit: "Request this session",
      sending: "Sending…",
      ok: "Thank you. Your request is in, and a confirmation is on its way to your email. We'll be in touch within one business hour.",
      err: "Something went wrong. Please try again, or email avraham@lalum.co.",
      need: "Please choose a day and time and enter a valid email.",
    },
    cmd: {
      title: "Quick schedule",
      placeholder: "e.g. Lecture on Aug 20 at 18:00 on algorithm risks",
      hint: "Press Enter to schedule. Esc to close.",
      scheduling: "Scheduling…",
      created: "Scheduled",
      withTravel: "travel time blocked",
      conflict: "This clashes with an existing event. Nothing was booked.",
      error: "Could not schedule. Try rephrasing.",
      min: "min",
    },
    schedule: {
      title: "Scheduling",
      agenda: "Agenda",
      none: "Nothing scheduled in this range.",
      travelTo: "Travel to",
      conflictBadge: "Overlap",
      reminders: "Reminders",
      remindersBefore: "before",
      tasks: "Tasks to time-block",
      addTask: "Add",
      taskPlaceholder: "A task to block time for",
      estimate: "min",
      place: "Place",
      placing: "Placing…",
      free: "Free slots",
      noSlots: "No free slots in the next days.",
      pickTask: "Pick a task, then a free slot to block it.",
      delete: "Delete",
      deleteConfirm: "Delete this event?",
      done: "Done",
      travelNote: "Travel time is estimated from the Herzliya office; live traffic applies when a maps key is set.",
      kinds: { lecture: "Lecture", meeting: "Meeting", zoom: "Zoom", phone: "Phone", block: "Work block", travel: "Travel" },
      hint: "Tip: press Cmd/Ctrl+K anywhere to schedule by typing.",
    },
  },

  home: {
    heroPill: "Code · Law · Economics",
    heroH1a: "Your breakthrough.",
    heroH1b: "Our legal architecture.",
    heroLede: "Legal, technological, and economic counsel for startups and breakthrough companies. We navigate the risks of tomorrow and engineer the competitive advantage of today.",
    statResponseStrong: "1-hour", statResponse: "response",
    statYearsStrong: "20+ years", statYears: "in high-stakes practice",
    statDefensibleStrong: "Defensible", statDefensible: "by design",
    cardTitle: "Tech-Legal & Strategic Advisory",
    advisoryBadge: "Advisory",
    advisoryIntro: "Tailored legal-technological consulting and strategic risk engineering for complex corporate and regulatory environments.",
    advisoryFormat: "Consultation format",
    advisoryInPersonTitle: "In-Person Session",
    advisoryInPersonBody: "A meeting at our Herzliya office (off-site by arrangement).",
    advisoryVirtualTitle: "Virtual Consultation",
    advisoryVirtualBody: "A secure, direct video conference via Zoom.",
    advisoryCta: "Schedule Advisory Session",
    aboutEyebrow: "Our positioning",
    aboutH2a: "We don't just interpret the law.",
    aboutH2b: "We design the technology beneath it.",
    aboutP1: "Most law firms advise on regulation without reading a single line of code. Most AI engineers build systems without understanding their IP exposure or their legality. We bridge that gap.",
    aboutP2: "We provide an absolute Tech-Legal envelope: full legal counsel, protected deployment of AI platforms inside your organization, and professional training for leadership and development teams. We build the technological, economic, and legal infrastructure that lets you move fast, legal, and safe.",
    pillarsEyebrow: "Our pillars",
    pillarsH2: "Three pillars of the engagement",
    engineEyebrow: "The Tech-Legal envelope",
    engineH2: "We embed inside your organization",
    engineP: "Beyond advice: we deploy protected AI, wire in continuous governance, and train the people who run it, so you move fast, legal, and safe.",
    whyEyebrow: "Why LALUM",
    whyH2: "A firm and an AI lab, under one roof",
    founderName: "Dr. Avraham Lalum",
    founderCreds1: "Attorney & Notary · Ph.D. Law & Economics",
    founderCreds2: "Head of AI, Lalum.",
    founderBio: "Founder of LALUM. Over two decades in high-stakes real estate and contract governance, now working at the Tech-Legal frontier where code, law, and economics meet.",
    founderOffice: "Office",
    founderDirect: "Direct",
    founderCv: "View full CV",
    logoAlt: "LALUM logo",
    storyEyebrow: "Our story",
    storyH2: "Judgment where code, law, and economics meet",
    storyP1: "LALUM works at the precise intersection of law, economics, and advanced technology (Legal AI), distilling legal practice to its sharpest form: pure strategy and data-driven risk management. We guide technology companies, businesses, and private clients through complex real estate transactions, the technological management of legal risk, and high-stakes contract governance, replacing bureaucratic drag with resilient, architectural protection of your commercial interests.",
    storyP2: "In parallel, the firm leads structured arbitration and mediation that pair decades of field experience with algorithmic analysis, to reach a resolution that is sharp, focused, and economically efficient.",
    faqEyebrow: "FAQ",
    faqH2a: "Navigating the",
    faqH2b: "Tech-Legal Convergence",
    faqShow: "Tap to see the questions",
    faqHide: "Hide the questions",
    ctaTitle: "Ready to begin?",
    ctaBody: "Your goal is clear. Now is the time to give it the right infrastructure.",
  },

  advisory: {
    heroPill: "Advisory & Mediation",
    heroH1a: "Counsel that reads the",
    heroH1b: "code and the contract.",
    heroLede: "Full-service legal, technological, and economic advisory for technology companies, and Decision-Oriented Mediation for the disputes that stall them. We map the exposure, structure the deal, and resolve the conflict, on a defensible record.",
    heroCta2: "Explore mediation (DOM) →",
    servicesEyebrow: "What we do",
    servicesH2: "Where we help",
    mediationEyebrow: "Decision-Oriented Mediation",
    mediationH2: "DOM: resolution, engineered",
    mediationP: "A proprietary, 8-module dispute resolution framework for complex real estate, corporate, and technology conflicts. Strictly time-bound, analytical, and built to reach an optimal, binding settlement without draining corporate resources.",
    testimonialsEyebrow: "In their words",
    testimonialsH2: "Trusted on high-stakes matters",
    engagementEyebrow: "Engagement",
    engagementH2: "Let's work together",
    mostPopular: "Most popular",
    ctaTitle: "Bring us the hard one",
    ctaBody: "Send us your most complex matter. We'll map the exposure and return a defensible path forward, within one business hour.",
  },

  training: {
    heroPill: "Professional Training",
    heroH1a: "Train the people who",
    heroH1b: "build and decide.",
    heroLede: "AI moves faster than any compliance memo. We give leadership and development teams the shared fluency to move fast without walking into legal, IP, or regulatory exposure: practical, role-specific, and grounded in real matters.",
    heroCta1: "Design a program",
    heroCta2: "See the curriculum →",
    audiencesEyebrow: "Who it's for",
    audiencesH2: "Two rooms, one shared language",
    curriculumEyebrow: "Curriculum",
    curriculumH2: "Modules we assemble to fit you",
    formatsEyebrow: "Formats",
    formatsH2: "However your team learns best",
    ctaTitle: "Build fluency into your team",
    ctaBody: "Tell us who's in the room and what they ship. We'll design a program around your real products and exposure.",
    ctaPrimary: "Design a program",
    course: {
      eyebrow: "LALUM Master Course",
      title: "Beyond the Traditional Firm",
      subtitle: "Step into the AI-driven app designed for instant legal and strategic execution.",
      formIntro: "Want a course tailored to your organization or to you personally? Leave your details and we will get back to you.",
      typeLabel: "This is for",
      typeOrg: "An organization",
      typeIndividual: "An individual",
      name: "Full name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "you@company.com",
      phone: "Phone",
      phonePlaceholder: "0500000000",
      note: "Anything we should know? (optional)",
      notePlaceholder: "Team size, focus, timing.",
      submit: "Leave my details",
      sending: "Sending…",
      ok: "Thank you. Your details are in, and we will get back to you within one business day.",
      err: "Something went wrong. Please try again, or email avraham@lalum.co.",
      need: "Please enter your name, a valid email, and a phone number.",
    },
  },

  insights: {
    heroPill: "The Algorist Notes",
    heroH1a: "On legal reasoning,",
    heroH1b: "machine memory, and defensibility.",
    heroLede: "Our continuing notes on what it takes to build judgment that holds up in front of a court.",
    ctaTitle: "Bring the same rigor to your matters",
    ctaBody: "Reading is good. Applying it to your own exposure is better. Start with a Tech-Legal Diagnostics session.",
  },

  legal: {
    eyebrow: "Legal",
    title: "Terms, privacy, and accessibility",
    disclaimer: "This page is general information for the LALUM website and is not legal advice or a binding agreement. For advice on your situation, book a consultation.",
    terms: {
      title: "Terms of use",
      body: [
        "By using this website you agree to use it lawfully and not to rely on its content as legal advice. Nothing here creates an attorney and client relationship; that begins only with a signed engagement.",
        "Content, brand, and materials on this site belong to LALUM and may not be copied or redistributed without permission.",
      ],
    },
    privacy: {
      title: "Privacy",
      body: [
        "We collect only what you send us: the details in a booking request or a message, plus the basic technical logs needed to run the site. We use them to respond to you and to operate and secure the service.",
        "We do not sell your information. Client matters are held under attorney and client confidentiality. You can ask what we hold about you and request correction or deletion.",
      ],
    },
    accessibility: {
      title: "Accessibility Statement",
      body: [
        "LALUM is committed to making its digital services accessible to the widest possible audience, including people with disabilities, in the belief that everyone has an equal right to use the web with dignity and independence.",
        "This website was built to conform with the Israeli Standard 5568 for web content accessibility and with the WCAG 2.1 guidelines at level AA, in line with the Equal Rights for Persons with Disabilities Regulations (Service Accessibility), 2013.",
        "Accessibility measures on this site include a clear and consistent heading structure, full keyboard navigation, a visible focus indicator on every interactive element, a skip to content link, sufficient color contrast, text that reflows and stays readable on mobile, descriptive labels for controls, and support for screen readers in both Hebrew and English.",
        "Some content is delivered through third party services, such as the scheduling and video meeting tools. We work to keep these usable, but their accessibility is partly controlled by the vendor. If you meet a barrier in any such component, please contact us and we will assist you directly.",
        "Despite our efforts, parts of the site may not yet be fully accessible. We treat every report as a priority and keep improving.",
        "Accessibility requests and reports: if you experience any difficulty, or need content in an alternative format, please contact our accessibility coordinator at avraham@lalum.co. Please describe the problem, the page, and the browser or device you used, and we will respond within one business day.",
        "This statement was last reviewed in July 2026.",
      ],
    },
    security: {
      title: "Security",
      body: [
        "We take the security of client information seriously. Data is transmitted over encrypted connections (HTTPS/TLS), and client records and files are stored on managed infrastructure with access controls and row-level security, so each client can reach only their own data.",
        "Access to the client area requires authentication. Documents you share through the portal are kept in a private store that only you and the firm can open. We apply the principle of least privilege and keep administrative access limited to the firm.",
        "No system is perfectly secure. If you believe you have found a vulnerability or a security concern, please contact us at avraham@lalum.co and we will respond promptly.",
      ],
    },
    aiLiability: {
      title: "Limitation of liability and use of AI systems",
      body: [
        "The firm hereby clarifies that some of the site's services, including the contract review and assessment bot, are operated and based on artificial intelligence (AI) systems and automated algorithms. The service is provided AS-IS. The firm, its managers, employees, or anyone on its behalf shall bear no liability whatsoever, direct, indirect, consequential, or special, for any damage, loss, or distress that may be caused to the user or to a third party as a result of relying on the outputs, remarks, analyses, or results produced by the bot.",
        "It is emphasized and clarified that the bot's outputs do not replace professional legal advice. Legal liability and a duty of care on the firm's part will arise only in connection with an opinion or individual legal advice provided directly by a licensed attorney on behalf of the firm, in writing, signed, and against a dedicated fee.",
      ],
    },
  },

  data: {
    heroRows: [
      { icon: "shield", title: "AI IP Protection & Licensing", sub: "Defensible IP & source-code protection", tag: "IP" },
      { icon: "settings", title: "Startup Scale & Contract Governance", sub: "Founder agreements, tech contracts & startup counsel", tag: "LEGAL" },
      { icon: "scale", title: "AI Regulation & Compliance", sub: "EU AI Act compliance & algorithmic risk", tag: "REG" },
      { icon: "gavel", title: "Mediation & Executive Advisory (DOM)", sub: "Strategic advisory & mediation for real-estate and tech disputes", tag: "DOM" },
    ] as Row[],
    pillars: [
      { icon: "shield", tag: "IP & Privacy", title: "Legal architecture & intellectual property", body: "Absolute protection for your organizational IP. Privacy-by-Design applied at the development stage, prevention of source-code contamination, and full alignment with local models and protected data environments." },
      { icon: "settings", tag: "Governance & Automation", title: "Contract governance & algorithmic risk", body: "Founder agreements, partner contracts, and complex distribution deals drafted with surgical precision. Data-driven control systems that bring the company to a state of zero friction in every transaction." },
      { icon: "scale", tag: "Strategic Scale", title: "Applied economics & strategic counsel", body: "Building hybrid business models, optimizing infrastructure and compute costs, and methodically preparing the company for funding rounds, due diligence, and international commercial deals." },
    ] as Pillar[],
    frameworks: [
      { code: "DEPLOY", title: "Protected AI deployment", icon: "brain", body: "We stand up AI platforms inside your organization on local models and RAG systems, Privacy-by-Design: capability without leaking IP or data." },
      { code: "GOVERN", title: "Embedded governance", icon: "shield", body: "Continuous contract governance and EU AI Act readiness wired into your workflow. Exposure is surfaced and mitigated before it becomes liability." },
      { code: "ENABLE", title: "Training & enablement", icon: "book", body: "Professional training for leadership and development teams, so the people building and deciding understand the legal and IP terrain they operate in." },
    ] as Framework[],
    why: [
      { icon: "spark", title: "Firm & lab", body: "Elite legal advisory and an AI-solutions practice under one roof, no hand-off, no translation loss." },
      { icon: "scale", title: "Algorithmic precision", body: "Legal logic governs the statistics, never the reverse. The engine augments judgment; it never replaces it." },
      { icon: "gavel", title: "Defensible by design", body: "Every decision sourced, dated, and reproducible, built to hold up in front of a judge." },
      { icon: "book", title: "20+ years, high stakes", body: "Deep experience where exposure is real: technology, real estate, and institutional governance." },
    ] as Why[],
    faqs: [
      { q: "What makes your firm different from traditional tech law firms?", a: "Traditional firms advise on law without understanding a single line of code. We bridge this gap. As a Tech-Legal boutique, we operate at the intersection of advanced law, applied economics, and AI architecture. We understand your product, RAG systems, and database structures from day one, ensuring your legal framework actively protects and enhances your technological assets." },
      { q: "How do you help startups protect their IP when using Generative AI?", a: "We implement strict Privacy-by-Design protocols. This includes establishing secure local environments (using open-source models) to prevent sensitive IP and customer data from leaking into public clouds. We also design robust AI usage policies to ensure your developers do not pollute your proprietary source code with third-party copyrighted material, which could otherwise jeopardize future funding or M&A." },
      { q: "What is the Clinic and Engine model?", a: "It is our dual-force operational framework. The Clinic represents our knowledge, research, and elite advisory, where we conduct masterclasses, executive training, and draft bespoke legal strategies. The Engine is our execution and integration arm, where we build secure AI platforms, automate contract governance, and engineer the actual tech-legal infrastructure for your business." },
      { q: "How do your strategic advisory sessions address complex traditional sectors like Real Estate alongside Tech?", a: "We do not treat technology and physical assets as separate worlds. Our strategic advisory sessions bridge the gap between traditional high-value sectors, such as complex real estate transactions, urban renewal (TAMA 38), and land taxation, and cutting-edge tech-legal architecture. By applying our dual expertise in Law & Economics and advanced contract automation, we restructure high-stakes real estate deals, manage joint-venture disputes, and optimize transaction workflows with data-driven precision, protecting your assets across both physical and digital landscapes." },
      { q: "What is DOM (Decision-Oriented Mediation) and how does it work?", a: "DOM is our proprietary, 8-module dispute resolution framework designed for complex real estate, corporate, and technology conflicts. Unlike traditional, drawn-out litigation or standard mediation, DOM is strictly time-bound, analytical, and highly structured. It combines law and economic modeling to drive the parties toward an optimal, legally binding settlement without draining corporate resources." },
      { q: "Can you help our enterprise comply with global AI regulations like the EU AI Act?", a: "Yes. We specialize in proactive regulatory engineering. We perform algorithmic risk assessments and align your tech stack with the strictest global frameworks (including the EU AI Act and advanced privacy laws). We turn compliance from a bureaucratic hurdle into a competitive advantage that builds trust with enterprise clients." },
      { q: "Do you build the actual AI platforms and automated workflows for clients?", a: "Absolutely. We do not just write contracts; we engineer the systems that govern them. We assist organizations in building secure, internal AI platforms, custom vector databases, and automated contract workflows (Agentic Workflows) that manage and mitigate risks in real-time with zero friction." },
      { q: "What does your full-service legal support for startups cover?", a: "We provide end-to-end legal and economic backing from inception to scale. This includes structuring sophisticated founders agreements, IP assignment, corporate governance, venture building, and representing the company in capital rounds (SAFE, Equity) and strategic M&A transactions." },
      { q: "Why is an economic perspective (Law & Economics) crucial for my tech business?", a: "Tech regulation is fundamentally economic. By applying rigorous Law & Economics principles, we do not just look at what is legally permissible; we model the financial and operational impact of legal structures on your business. This ensures your legal architecture supports sustainable growth and maximizes company valuation." },
      { q: "How do your corporate training and masterclasses work?", a: "We deliver highly specialized, actionable masterclasses and workshops for boards of directors, executive teams, and R&D departments. We translate complex tech-legal concepts, algorithmic risks, and shifting regulations into practical, business-oriented decision-making tools." },
      { q: "How do we start working with you?", a: "We begin with a strategic Tech-Legal Diagnostics session. In this initial meeting, we map your current technical architecture, corporate structure, and regulatory exposure to identify immediate vulnerabilities and design a tailored roadmap for your venture." },
    ] as Faq[],
    advisoryServices: [
      { icon: "shield", title: "Intellectual property protection", body: "Building a defensible IP layer around your technology: patents, trade secrets, and proprietary models, engineered as a competitive advantage that holds up to investor and court scrutiny." },
      { icon: "settings", title: "Automated contract governance", body: "Standard frameworks, lifecycle review, and monitoring so every agreement stays consistent, current, and enforceable, with zero friction in each transaction." },
      { icon: "scale", title: "Regulatory risk management", body: "Mapping and managing advanced regulatory exposure, including the EU AI Act, from the development stage, to prevent critical legal and economic exposure before it forms." },
      { icon: "brain", title: "Secure data architecture", body: "Guidance on local-model and RAG architecture with Privacy-by-Design: privacy and security built into the foundation, never bolted on afterwards." },
      { icon: "file", title: "Venture & startup counsel", body: "A strategic envelope for technology companies and individuals: incorporation, funding rounds, founder and employee agreements, and ongoing counsel for the AI era." },
      { icon: "search", title: "Technology due diligence", body: "Legal and technical due diligence for deals and raises: identifying exposure in IP, data, and regulation before it becomes a cost." },
    ] as Service[],
    domModules: [
      { icon: "scale", title: "Structured, time-bound process", body: "An 8-module framework that replaces drawn-out litigation with a strictly time-bound, analytical path to resolution." },
      { icon: "brain", title: "Law and economic modeling", body: "Every position is modeled through both legal doctrine and economic impact, driving parties toward an optimal, binding settlement." },
      { icon: "shield", title: "Defensible, binding outcome", body: "A settlement that is legally binding and built on a documented, defensible record, without draining corporate resources." },
    ] as Module[],
    testimonials: [
      { quote: "LALUM rebuilt our entire contract-governance framework. The speed and structure changed how the whole organization operates.", attr: "CFO, urban economic corporation" },
      { quote: "They understand construction risk the way our engineers understand a load-bearing wall, and they back it with algorithmic rigor.", attr: "General Counsel, infrastructure group" },
      { quote: "The risk model flagged an exposure our previous advisors missed for years. This is what algorithmic precision looks like in practice.", attr: "CEO, real-estate developer" },
    ] as Testimonial[],
    plans: [
      { name: "Fixed-scope mandate", tagline: "A defined engagement, a predictable cost", best: "Best for: a single high-stakes matter with a clear deliverable", popular: false, features: ["Response time under one hour", "Algorithmic risk assessment", "Court-ready deliverable", "Fixed price, no hourly billing"], cta: "Request a scope proposal" },
      { name: "Retainer partnership", tagline: "Your embedded legal and AI team", best: "Best for: growing organizations with ongoing exposure", popular: true, features: ["Priority response under one hour", "A dedicated attorney", "Continuous risk monitoring (RECIR)", "Unlimited advisory"], cta: "Book a consultation" },
    ] as Plan[],
    audiences: [
      { icon: "spark", title: "Leadership & executives", body: "The judgment layer. Enough fluency to sponsor AI initiatives, read the risk, and ask the right questions before signing off.", points: ["Where AI creates legal & IP exposure", "EU AI Act obligations at board level", "Governance decisions you actually own"] },
      { icon: "brain", title: "Development & product teams", body: "The build layer. Concrete practices so what ships is compliant, IP-clean, and defensible from the first commit.", points: ["Privacy-by-Design in the pipeline", "Avoiding source-code & data contamination", "Local models & RAG done safely"] },
    ] as Audience[],
    trainingModules: [
      { icon: "shield", title: "AI risk & IP foundations", body: "The core landscape: where intellectual property, data, and liability actually sit in an AI product." },
      { icon: "scale", title: "EU AI Act in practice", body: "Risk classification, obligations, and documentation, translated from regulation into engineering tasks." },
      { icon: "file", title: "Contract & data governance", body: "What your agreements and data flows must cover when AI is in the loop, and how to keep them enforceable." },
      { icon: "brain", title: "Secure architecture patterns", body: "Privacy-by-Design, local models, and RAG: the patterns that keep capability from leaking IP or data." },
      { icon: "search", title: "Reading the exposure", body: "How to spot legal and economic exposure early: a shared checklist for product reviews and go/no-go calls." },
      { icon: "gavel", title: "From incident to defense", body: "What defensible means in practice: sourcing, dating, and the record that survives scrutiny." },
    ] as Module[],
    formats: [
      { meta: "Half-day", title: "Executive briefing", body: "A sharp session for leadership: the risk picture and the decisions they own." },
      { meta: "4 to 6 weeks", title: "Team program", body: "A structured track for development and product teams, applied to your own stack." },
      { meta: "Ongoing", title: "Embedded advisor", body: "Recurring sessions and office hours as your product and the regulation evolve." },
    ] as Format[],
    articles: [
      {
        slug: "legal-logic", icon: "scale", category: "Doctrine",
        title: "Why legal logic must govern the statistics",
        dek: "A model that predicts language is not a model that reasons about law. The gap between the two is where cases are won and lost.",
        date: "Jul 2026", read: "6 min read",
        blocks: [
          { type: "p", text: "A large language model is, at its core, an extraordinary instrument of correlation. It has read more contracts, rulings, and statutes than any human ever could, and it can predict, with uncanny fluency, what a legal sentence tends to look like. That fluency is seductive, and it is precisely why it is dangerous when left to run legal reasoning unsupervised." },
          { type: "p", text: "The danger is not that the machine will think like a person. It is that a person will begin to think like the machine, mistaking what is statistically common for what is legally correct. The most frequent clause is not the most defensible one. The most probable answer is not the one a court will accept." },
          { type: "quote", text: "Legal logic governs the statistics, never the reverse." },
          { type: "h2", text: "Where correlation breaks" },
          { type: "p", text: "Consider an indemnity provision that appears in ninety percent of vendor agreements. A statistical model will happily reproduce it, because it is common. But commonality tells you nothing about enforceability in your jurisdiction, under your governing law, against your specific counterparty. The doctrine, the actual chain of legal reasoning, is invisible to a system that only measures frequency." },
          { type: "p", text: "This is the failure mode we engineer against. Every output that leaves LALUM passes through a doctrinal layer before it is ever considered finished:" },
          { type: "list", items: ["The statistical draft is generated and treated as a hypothesis, not an answer.", "That hypothesis is cross-examined against current doctrine, statute, and controlling precedent.", "Anything that survives is sourced and dated; anything that cannot be defended is discarded."] },
          { type: "h2", text: "Judgment is the product" },
          { type: "p", text: "The automation is real, and it is powerful, but it exists to clear the desk, not to make the decision. What is left after the repetitive work is removed is the part that always mattered: judgment, strategy, and the willingness to be accountable for a position. That is the work of a lawyer, and it is the work we protect." },
          { type: "p", text: "An algorithm can tell you what is likely. Only legal logic can tell you what is right, and only a licensed attorney can sign their name to it." },
        ],
      },
      {
        slug: "memory", icon: "brain", category: "Architecture",
        title: "Long-term memory: giving legal AI a case history",
        dek: "Most legal tools forget the moment you close the tab. An organization's legal knowledge deserves better than amnesia.",
        date: "Jun 2026", read: "8 min read",
        blocks: [
          { type: "p", text: "Ask a generic legal assistant the same question twice and it answers as a stranger both times. It has no memory of your prior matters, no sense of your risk posture, no record of the compromise you reached last quarter and why. Every interaction starts from zero. For casual questions that is fine. For an organization carrying real exposure, it is a structural weakness." },
          { type: "p", text: "The value of a great in-house counsel is not that they answer fast, it is that they remember. They know which supplier always pushes for unlimited liability, which clause your board will never approve, which past dispute still shapes how you contract today. That institutional memory is the asset. It is also exactly what most legal AI throws away." },
          { type: "h2", text: "The Deep Operational Model" },
          { type: "p", text: "LALUM's DOM framework was built to hold that memory. Rather than treating your documents as a pile of files to be searched, it models your legal reality as a living system, every contract, obligation, and dependency represented as a node that can be queried, monitored, and reasoned about over time." },
          { type: "quote", text: "We do not ask questions of a stranger. We give the system a memory that improves with every new file." },
          { type: "p", text: "Because the model persists, it compounds. Each new matter does not just get resolved, it makes the next one sharper:" },
          { type: "list", items: ["Precedent from your own past deals informs new drafts, not just the public corpus.", "Recurring counterparties and their patterns are remembered across matters.", "A position taken in one contract is checked for consistency against every other."] },
          { type: "h2", text: "Memory you own" },
          { type: "p", text: "This memory is yours alone. Your case history trains your model, it is never pooled with, or exposed to, other clients. Confidentiality here is not a setting to be toggled; it is a professional obligation that predates the technology by centuries." },
          { type: "p", text: "The result is legal support that does what a trusted advisor does: it remembers, it improves, and it grows more valuable the longer you work with it." },
        ],
      },
      {
        slug: "defensible", icon: "shield", category: "Practice",
        title: "Defensible by design: what survives cross-examination",
        dek: "There is a difference between an answer you can act on and an answer you can defend in front of a judge. We build for the second.",
        date: "Jun 2026", read: "5 min read",
        blocks: [
          { type: "p", text: "Speed is easy to demonstrate and easy to sell. Defensibility is neither, which is exactly why it is the property that matters most. A fast answer that collapses under scrutiny is worse than no answer at all, because it has already been relied upon by the time it fails." },
          { type: "p", text: "So we ask a harder question of every deliverable before it leaves us: would this survive cross-examination? Not is it plausible, not does it sound right, but could a licensed attorney stand behind it, under challenge, in front of a court?" },
          { type: "h2", text: "Three properties" },
          { type: "p", text: "A defensible output has three properties, and the SRME framework enforces all three before sign-off:" },
          { type: "list", items: ["Sourced: every position traces to the authority it rests on, not to a confident guess.", "Dated: it names the version of the law it relied upon, so it can be tested against the law as it stood.", "Reproducible: the same inputs yield the same reasoning, word for word, every time."] },
          { type: "quote", text: "What cannot be defended in front of a judge never appears in the deliverable." },
          { type: "h2", text: "The human signature" },
          { type: "p", text: "Technology gets us to a defensible draft quickly. It does not get to skip the last step. Every output is reviewed and signed by a qualified attorney who is personally accountable for it. The AI assists; the lawyer decides. That signature is not a formality, it is the whole point." },
          { type: "p", text: "Defensibility, in the end, is not a feature you add at the end. It is a discipline you design in from the first line, and then refuse to compromise." },
        ],
      },
    ] as Article[],
  },
};

export type Dict = typeof en;

const he: Dict = {
  ui: {
    langName: "עברית",
    otherLangName: "English",
    otherLangShort: "EN",
    nav: { home: "בית", advisory: "ייעוץ וגישור", training: "הדרכה", insights: "תובנות" },
    tabs: { home: "בית", advisory: "ייעוץ", training: "הדרכה", book: "פגישה", client: "לקוחות" },
    share: { aria: "שיתוף LALUM", copied: "הקישור הועתק", text: "LALUM, ייעוץ משפטי, טכנולוגי ואסטרטגי" },
    whatsapp: { aria: "צ'אט מהיר בוואטסאפ", msg: "שלום, הגעתי דרך אפליקציית LALUM ואשמח לדבר." },
    consent: {
      pre: "אני מאשר/ת קבלת חומר שיווקי ומידע מ-LALUM בווטסאפ, בדוא\"ל, ב-SMS, טלפונית וכיוצ\"ב, ומסכים/ה ל",
      terms: "תקנון",
      mid: " ול",
      privacy: "מדיניות הפרטיות",
      post: ". ניתן להסיר את עצמכם בכל עת.",
    },
    guide: {
      open: "מדריך",
      title: "מדריך שימוש מהיר",
      intro: "כל מה שאפשר לעשות כאן, בחמישה צעדים. הכל במקום אחד, מהטלפון או מהמחשב.",
      close: "סגירה",
      steps: [
        { title: "כניסה לאזור האישי", body: "נרשמים פעם אחת עם אימייל וסיסמה, ובכל פעם הבאה פשוט מתחברים.", cta: "כניסה" },
        { title: "שליחת הודעה למשרד", body: "בוחרים נושא, כותבים ושולחים. המענה חוזר במייל וגם בשרשור באזור האישי.", cta: "לאזור האישי" },
        { title: "העברת מסמך", body: "מעלים קבצים בצורה מאובטחת (PDF, תמונות ומסמכי אופיס, עד 25MB). המשרד מקבל התראה מיד.", cta: "לאזור האישי" },
        { title: "קביעת פגישה", body: "בוחרים יום ושעה, מוסיפים משפט קצר, והמשרד מאשר בתוך שעת עסקים אחת.", cta: "קביעת פגישה" },
        { title: "שאלה ל-LEX", body: "שואלים את העוזר החכם שאלה כללית, או מצרפים חוזה לקבלת הערות.", cta: "פתיחת צ'אט" },
      ],
      moreTitle: "עוד",
      qa: "שאלות ותשובות",
      articles: "מאמרים",
      download: "התקנת האפליקציה",
      aiNote: "LEX הוא כלי מבוסס בינה מלאכותית. תשובותיו אינן ייעוץ משפטי ואינן מחליפות בדיקה של עורך דין מוסמך.",
    },
    clientLogin: "כניסת לקוחות",
    clientPortal: "אזור לקוחות",
    seeWhatWeDo: "מה אנחנו עושים ←",
    initiateRisk: "לפתיחת הערכת סיכונים",
    skipToContent: "דלג לתוכן",
    footerLinks: { home: "בית", advisory: "ייעוץ וגישור", training: "הדרכה", insights: "תובנות", login: "כניסת לקוחות", terms: "תנאים", privacy: "פרטיות", accessibility: "נגישות", security: "אבטחה", cookies: "הגדרות קובצי Cookie", qa: "שאלות ותשובות", articles: "מאמרים" },
    footer: { explore: "ניווט", client: "לקוחות", contact: "צור קשר", book: "לקביעת שיחה", city: "הרצליה", tagline: "ייעוץ Tech-Legal ואסטרטגי לסטארטאפים ולחברות פורצות דרך.", rights: "כל הזכויות שמורות.", downloadTitle: "הורידו את האפליקציה והתחילו לעבוד בצורה מהירה ומקצועית.", downloadSub: "סרקו את קוד ה-QR באמצעות מצלמת הטלפון כדי להוריד את האפליקציה.", qrAlt: "קוד QR לפתיחת lalumapp.com", follow: "עקבו אחרי LALUM", linkedin: "LALUM בלינקדאין", facebook: "LALUM בפייסבוק", instagram: "LALUM באינסטגרם", website: "אתר המשרד" },
    cookie: { title: "הגדרות קובצי Cookie", intro: "אנחנו משתמשים רק במה שנדרש להפעלת האתר. קובצי Cookie חיוניים שומרים על תפקוד האפליקציה; ניתוח נתונים הוא רשות וכבוי אלא אם אישרתם.", essential: "חיוניים", essentialNote: "תמיד פעילים. נדרשים לתפקוד האתר (התחברות, אבטחה, העדפות).", analytics: "ניתוח נתונים", analyticsNote: "סטטיסטיקת שימוש אנונימית שעוזרת לנו להשתפר. כבוי כברירת מחדל.", accept: "אישור הכול", reject: "דחיית לא-חיוניים", save: "שמירת הבחירות", saved: "בחירות ה-Cookie נשמרו.", banner: "אנחנו משתמשים בקובצי Cookie חיוניים להפעלת האתר, ובניתוח נתונים רק בהסכמתכם.", manage: "ניהול" },
    a11y: { open: "תפריט נגישות", title: "נגישות", textSize: "גודל טקסט", contrast: "ניגודיות גבוהה", links: "הדגשת קישורים", readable: "גופן קריא", motion: "הפחתת תנועה", reset: "איפוס", statement: "הצהרת נגישות" },
    chat: {
      title: "LEX · LALUM",
      subtitle: "מידע משפטי כללי, לא ייעוץ משפטי",
      greeting: "היי, אני LEX, עוזר ה-AI המשפטי של LALUM. שאלו שאלה משפטית כללית, או צרפו הסכם ואחזיר הערות. בנושאי סטארטאפים, IP, רגולציית AI, חוזים או גישור.",
      placeholder: "שאלו שאלה משפטית…",
      send: "שליחת הודעה",
      open: "צ׳אט עם העוזר של LALUM",
      thinking: "חושב…",
      demoReply: "זו גרסת הדגמה, ולכן העוזר החי אינו מחובר כאן. לשאלה ספציפית, קבעו שיחה ונחזור אליכם בתוך שעת עסקים אחת. זהו מידע כללי, לא ייעוץ משפטי.",
      errorReply: "משהו השתבש בפנייה לעוזר. נסו שוב עוד רגע, או קבעו אתנו שיחה.",
      attach: "העלאת הסכם לבחינה / קבלת הערות",
      attaching: "קורא את הקובץ…",
      attached: "מצורף",
      remove: "הסרה",
      fileErr: "לא הצלחנו לקרוא את הקובץ. נסו PDF או DOCX.",
      reviewPrefix: "הסכם מצורף לבדיקה",
      reviewAsk: "אנא בדוק את ההסכם ותן את הערותיך.",
      disclaimer: "*המערכת מבוססת על בינה מלאכותית (AI). המידע וההערות המופקים על ידי הבוט אינם מהווים ייעוץ משפטי, ואין לחברה או למי מטעמה כל אחריות לנזק, ישיר או עקיף, לרבות לתוצאות השימוש במידע זה. האחריות הבלעדית והמלאה של המשרד חלה אך ורק על ייעוץ משפטי פרטני הניתן בכתב וכנגד תשלום מסודר.",
    },
    login: {
      eyebrow: "אזור הלקוחות",
      signIn: "התחברות",
      createAccount: "יצירת חשבון",
      subtitle: "גישה להודעות, למסמכים, לפגישות ולתשלומים שלכם.",
      demo: "מצב הדגמה: אין חיבור ל-Supabase, ולכן כל אימייל וסיסמה באורך 6 תווים ומעלה יחברו אתכם מקומית.",
      confirmEmail: "בדקו את תיבת הדואר לאישור האימייל, ואז התחברו.",
      email: "אימייל",
      password: "סיסמה",
      emailPlaceholder: "you@company.com",
      passwordPlaceholder: "לפחות 6 תווים",
      pleaseWait: "רגע…",
      newHere: "חדשים ב-LALUM? ",
      haveAccount: "כבר יש לכם חשבון? ",
    },
    portal: {
      eyebrow: "אזור לקוחות",
      welcome: "שמחים לראותכם",
      signOut: "התנתקות",
      demo: "מצב הדגמה: Supabase אינו מוגדר, ולכן השליחות למטה מדומות מקומית ואינן נשלחות לשום מקום. הגדירו את VITE_SUPABASE_URL ואת VITE_SUPABASE_ANON_KEY כדי לחבר את ה-backend החי.",
      book: {
        title: "קביעת פגישת אבחון",
        step1: "1 · בחירת יום",
        step2: "2 · בחירת שעה",
        step3: "3 · במה מדובר? (רשות)",
        topicPlaceholder: "בקצרה, העניין שתרצו למפות.",
        submit: "בקשת מועד זה",
        sending: "שולח…",
        okPrefix: "התקבלה בקשה ל-",
        okAt: "בשעה",
        okSuffix: "נאשר בתוך שעת עסקים אחת.",
        err: "לא הצלחנו לשלוח את הבקשה. נסו שוב.",
      },
      messages: {
        title: "פנייה למשרד",
        intro: "שלחו לנו הודעה מאובטחת. כל פנייה מטופלת דרך מערכת שירות הלקוחות של המשרד, ואנחנו משיבים במייל.",
        category: "נושא",
        categories: { general: "פנייה כללית", booking: "פגישה / תיאום", documents: "מסמכים", billing: "חיוב וחשבונות" },
        subject: "כותרת (רשות)",
        subjectPlaceholder: "כותרת קצרה",
        body: "הודעה",
        bodyPlaceholder: "איך נוכל לעזור?",
        submit: "שליחת הודעה",
        sending: "שולח…",
        ok: "ההודעה נשלחה. נשיב לכתובת המייל שלכם בהקדם.",
        err: "לא הצלחנו לשלוח את ההודעה. נסו שוב.",
        note: "פגישות במשרד בהרצליה, בטלפון או בזום ניתן לתאם ישירות. פגישות מחוץ למשרד מתואמות מראש מול המשרד.",
      },
      files: {
        title: "שיתוף מסמכים",
        intro: "העלו מסמכים באופן מאובטח. רק אתם והמשרד יכולים לגשת אליהם. אנחנו מקבלים התראה ברגע שקובץ מגיע.",
        choose: "בחירת קובץ",
        uploading: "מעלה…",
        ok: "הקובץ שותף. המשרד קיבל התראה.",
        err: "ההעלאה נכשלה. נסו שוב.",
        tooBig: "הקובץ חורג ממגבלת 25 MB.",
        yourFiles: "הקבצים שלכם",
        none: "עדיין לא שותפו קבצים.",
        download: "הורדה",
        remove: "הסרה",
        confirmRemove: "להסיר את הקובץ?",
        hint: "עד 25 MB לקובץ. נתמכים PDF, תמונות ומסמכי אופיס.",
      },
      thread: {
        title: "ההתכתבות שלכם",
        awaiting: "ממתין לתשובה מהמשרד.",
        replyLabel: "תשובה מ-LALUM",
      },
      inbox: {
        title: "תיבת פניות הלקוחות",
        intro: "כל הודעת לקוח. נסחו תשובה בעזרת AI, ערכו אותה, ואשרו לשליחה.",
        none: "עדיין אין הודעות מלקוחות.",
        from: "מאת",
        draftAi: "ניסוח בעזרת AI",
        drafting: "מנסח…",
        replyPlaceholder: "כתבו או ערכו את התשובה, ואז אשרו לשליחה…",
        send: "אישור ושליחה",
        sending: "שולח…",
        replied: "נענה",
        newBadge: "חדש",
      },
      billing: {
        title: "תשלומים",
        intro: "אבני הדרך לתשלום שלכם. שלמו באופן מאובטח ב-Bit, Apple Pay, Google Pay או כרטיס אשראי.",
        none: "אין תשלומים לביצוע כרגע.",
        pay: "לתשלום",
        paying: "פותח עמוד תשלום מאובטח…",
        amount: "סכום",
        statusLabels: { pending: "ממתין לתשלום", sent: "ממתין לתשלום", paid: "שולם", failed: "התשלום נכשל" },
        payErr: "לא הצלחנו לפתוח את עמוד התשלום. נסו שוב.",
        adminTitle: "חיובים",
        adminIntro: "צרו אבן דרך לתשלום עבור לקוח. הוא יוכל לשלם אותה מהפורטל.",
        clientEmail: "אימייל הלקוח",
        clientEmailPh: "client@company.com",
        itemTitle: "עבור מה התשלום?",
        itemTitlePh: "ריטיינר, אבן דרך, ייעוץ",
        amountPh: "0.00",
        create: "יצירת אבן דרך",
        creating: "יוצר…",
        createdOk: "אבן הדרך נוצרה.",
        err: "משהו השתבש. נסו שוב.",
        allTitle: "כל אבני הדרך",
        copyLink: "העתקת קישור תשלום",
        copied: "הועתק",
      },
    },
    article: {
      allArticles: "לכל המאמרים",
      by: "מאת ד״ר אברהם ללום",
      seal: "עורך דין ונוטריון · Ph.D. במשפט וכלכלה · ראש מחלקת ה-AI, ללום.",
      keepReading: "המשך קריאה",
      keepReadingHead: "החילו את אותה קפדנות על העניינים שלכם.",
    },
    bookPage: {
      navCta: "לקביעת שיחה",
      eyebrow: "קביעת פגישה",
      title: "לתיאום פגישת אבחון Tech-Legal",
      subtitle: "בחרו מועד שנוח לכם. בלי צורך בחשבון. נמפה את הארכיטקטורה, המבנה והחשיפה הרגולטורית שלכם, ונחזיר מפת דרכים מותאמת.",
      subtitleLive: "בחרו מועד למטה. תקבלו אישור מיידי במייל והזמנה ליומן, והפגישה נכנסת אוטומטית ליומן שלנו.",
      step1: "1 · בחירת יום",
      step2: "2 · בחירת שעה",
      name: "שם מלא",
      namePlaceholder: "השם שלכם",
      email: "אימייל",
      emailPlaceholder: "you@company.com",
      topic: "3 · במה מדובר? (רשות)",
      topicPlaceholder: "בקצרה, העניין שתרצו למפות.",
      submit: "לשליחת הבקשה",
      sending: "שולח…",
      ok: "תודה. הבקשה התקבלה, ואישור בדרך לאימייל שלכם. נחזור אליכם בתוך שעת עסקים אחת.",
      err: "משהו השתבש. נסו שוב, או כתבו ל-avraham@lalum.co.",
      need: "בחרו יום ושעה והזינו אימייל תקין.",
    },
    cmd: {
      title: "תזמון מהיר",
      placeholder: "למשל: הרצאה ב-20 באוגוסט בשעה 18:00 בנושא סיכוני אלגוריתמים",
      hint: "Enter לתזמון. Esc לסגירה.",
      scheduling: "מתזמן…",
      created: "נקבע ביומן",
      withTravel: "זמן נסיעה נחסם",
      conflict: "יש התנגשות עם אירוע קיים. שום דבר לא נקבע.",
      error: "לא הצלחנו לתזמן. נסו לנסח מחדש.",
      min: "דק׳",
    },
    schedule: {
      title: "יומן וניהול",
      agenda: "סדר יום",
      none: "אין אירועים בטווח הזה.",
      travelTo: "נסיעה אל",
      conflictBadge: "חפיפה",
      reminders: "תזכורות",
      remindersBefore: "לפני",
      tasks: "משימות לחסימת זמן",
      addTask: "הוספה",
      taskPlaceholder: "משימה לחסימת זמן",
      estimate: "דק׳",
      place: "שיבוץ",
      placing: "משבץ…",
      free: "חלונות פנויים",
      noSlots: "אין חלונות פנויים בימים הקרובים.",
      pickTask: "בחרו משימה, ואז חלון פנוי כדי לשבץ אותה.",
      delete: "מחיקה",
      deleteConfirm: "למחוק את האירוע?",
      done: "בוצע",
      travelNote: "זמן הנסיעה מוערך מהמשרד בהרצליה; נתוני תנועה חיים חלים כשמוגדר מפתח מפות.",
      kinds: { lecture: "הרצאה", meeting: "פגישה", zoom: "זום", phone: "טלפון", block: "בלוק עבודה", travel: "נסיעה" },
      hint: "טיפ: לחצו Cmd/Ctrl+K בכל מקום כדי לתזמן בהקלדה.",
    },
  },

  home: {
    heroPill: "קוד · חוק · כלכלה",
    heroH1a: "הפריצה שלכם.",
    heroH1b: "הארכיטקטורה המשפטית שלנו.",
    heroLede: "ייעוץ משפטי, טכנולוגי וכלכלי לסטארטאפים ולחברות פורצות דרך. אנחנו מנווטים את הסיכונים של מחר ובונים את היתרון התחרותי של היום.",
    statResponseStrong: "שעה", statResponse: "זמן תגובה",
    statYearsStrong: "20+ שנים", statYears: "בפרקטיקה בסיכון גבוה",
    statDefensibleStrong: "בר-הגנה", statDefensible: "מעצם התכנון",
    cardTitle: "ייעוץ Tech-Legal ואסטרטגי",
    advisoryBadge: "ייעוץ",
    advisoryIntro: "ייעוץ משפטי-טכנולוגי מותאם והנדסת סיכונים אסטרטגית לסביבות תאגידיות ורגולטוריות מורכבות.",
    advisoryFormat: "פורמט הפגישה",
    advisoryInPersonTitle: "פגישה פרונטלית",
    advisoryInPersonBody: "פגישה במשרד שלנו בהרצליה (מחוץ למשרד בתיאום מראש).",
    advisoryVirtualTitle: "פגישת וידאו",
    advisoryVirtualBody: "שיחת וידאו מאובטחת וישירה דרך Zoom.",
    advisoryCta: "לתיאום פגישת ייעוץ",
    aboutEyebrow: "המיצוב שלנו",
    aboutH2a: "אנחנו לא רק מפרשים את החוק.",
    aboutH2b: "אנחנו מתכננים את הטכנולוגיה שמתחתיו.",
    aboutP1: "רוב המשרדים מייעצים על רגולציה בלי לקרוא שורת קוד אחת. רוב מהנדסי ה-AI בונים מערכות בלי להבין את חשיפת ה-IP או את החוקיות שלהן. אנחנו מגשרים על הפער הזה.",
    aboutP2: "אנחנו מספקים מעטפת Tech-Legal מלאה: ייעוץ משפטי מקיף, הטמעה מוגנת של פלטפורמות AI בתוך הארגון, והדרכה מקצועית להנהלה ולצוותי הפיתוח. אנחנו בונים את התשתית הטכנולוגית, הכלכלית והמשפטית שמאפשרת לכם לנוע מהר, כחוק ובביטחון.",
    pillarsEyebrow: "עמודי התווך שלנו",
    pillarsH2: "שלושה עמודי תווך של ההתקשרות",
    engineEyebrow: "המעטפת ה-Tech-Legal",
    engineH2: "אנחנו משתלבים בתוך הארגון שלכם",
    engineP: "מעבר לייעוץ: אנחנו מטמיעים AI מוגן, מחווטים ממשל מתמשך, ומכשירים את האנשים שמפעילים אותו, כדי שתנועו מהר, כחוק ובביטחון.",
    whyEyebrow: "למה LALUM",
    whyH2: "משרד ומעבדת AI, תחת קורת גג אחת",
    founderName: "ד״ר אברהם ללום",
    founderCreds1: "עורך דין ונוטריון · Ph.D. במשפט וכלכלה",
    founderCreds2: "ראש מחלקת ה-AI, ללום.",
    founderBio: "מייסד LALUM. מעל שני עשורים בנדל״ן ובממשל חוזים ברמת סיכון גבוהה, כיום בחזית ה-Tech-Legal שבה נפגשים קוד, משפט וכלכלה.",
    founderOffice: "משרד",
    founderDirect: "נייד",
    founderCv: "לצפייה בקורות החיים המלאים",
    logoAlt: "הלוגו של LALUM",
    storyEyebrow: "הסיפור שלנו",
    storyH2: "שיקול דעת במפגש שבין קוד, חוק וכלכלה",
    storyP1: "לאורך שני עשורים בנדל״ן בסיכון גבוה ובממשל חוזים, ובאופן הולך וגובר באלגוריתמים שמעצבים כיום חשיבה משפטית, חזר אותו דפוס: שיקול דעת מבריק נקבר תחת עבודה שאף עורך דין לא אמור לעשות ידנית.",
    storyP2: "לכן הפכנו לאוטומטי כל דבר שאינו דורש תואר במשפטים. מה שנותר הוא עבודת עורך דין טהורה: אסטרטגיה, שיקול דעת, וההכרעות שנושאות חשיפה אמיתית, שנשמרות מובנות, מנוטרות ובנות-הגנה באמצעות המסגרות DOM, RECIR ו-SRME.",
    faqEyebrow: "שאלות ותשובות",
    faqH2a: "לנווט את",
    faqH2b: "התכנסות ה-Tech-Legal",
    faqShow: "לחצו כדי לראות את השאלות",
    faqHide: "להסתרת השאלות",
    ctaTitle: "מוכנים להתחיל?",
    ctaBody: "המטרה שלכם ברורה. עכשיו הזמן לתת לה את התשתית הנכונה.",
  },

  advisory: {
    heroPill: "ייעוץ וגישור",
    heroH1a: "ייעוץ שקורא את",
    heroH1b: "הקוד ואת החוזה.",
    heroLede: "ייעוץ משפטי, טכנולוגי וכלכלי מקצה לקצה לחברות טכנולוגיה, וגישור מוכוון-הכרעה (DOM) לסכסוכים שמעכבים אותן. אנחנו ממפים את החשיפה, בונים את העסקה, ופותרים את הסכסוך, על בסיס תיעוד בר-הגנה.",
    heroCta2: "להכיר את הגישור (DOM) ←",
    servicesEyebrow: "מה אנחנו עושים",
    servicesH2: "היכן אנחנו מסייעים",
    mediationEyebrow: "גישור מוכוון-הכרעה",
    mediationH2: "DOM: הכרעה, מהונדסת",
    mediationP: "מסגרת קניינית בת 8 מודולים ליישוב סכסוכים מורכבים בנדל״ן, בתאגידים ובטכנולוגיה. תחומה בזמן, אנליטית, ובנויה להגיע להסדר מיטבי ומחייב בלי לרוקן משאבים ארגוניים.",
    testimonialsEyebrow: "במילים שלהם",
    testimonialsH2: "אמון בעניינים בסיכון גבוה",
    engagementEyebrow: "התקשרות",
    engagementH2: "בואו נעבוד יחד",
    mostPopular: "הנפוץ ביותר",
    ctaTitle: "הביאו לנו את הקשה ביותר",
    ctaBody: "שלחו לנו את העניין המורכב ביותר שלכם. נמפה את החשיפה ונחזיר מסלול פעולה בר-הגנה, בתוך שעת עסקים אחת.",
  },

  training: {
    heroPill: "הדרכה מקצועית",
    heroH1a: "הכשירו את מי ש",
    heroH1b: "בונה ומכריע.",
    heroLede: "AI נע מהר יותר מכל נוהל ציות. אנחנו מקנים להנהלה ולצוותי הפיתוח שפה משותפת שמאפשרת לנוע מהר בלי להיכנס לחשיפה משפטית, קניינית או רגולטורית: מעשי, מותאם לתפקיד, ומעוגן בעניינים אמיתיים.",
    heroCta1: "לתכנון תוכנית",
    heroCta2: "לצפייה בקוריקולום ←",
    audiencesEyebrow: "למי זה מיועד",
    audiencesH2: "שני חדרים, שפה משותפת אחת",
    curriculumEyebrow: "קוריקולום",
    curriculumH2: "מודולים שאנחנו מרכיבים בהתאמה אליכם",
    formatsEyebrow: "פורמטים",
    formatsH2: "איך שהצוות שלכם לומד הכי טוב",
    ctaTitle: "בנו שפה משותפת בצוות שלכם",
    ctaBody: "ספרו לנו מי בחדר ומה הם משגרים. נתכנן תוכנית סביב המוצרים והחשיפה האמיתיים שלכם.",
    ctaPrimary: "לתכנון תוכנית",
    course: {
      eyebrow: "קורס מאסטר של LALUM",
      title: "מעבר לפירמה המסורתית",
      subtitle: "היכנסו לאפליקציה מבוססת ה-AI שנבנתה לביצוע משפטי ואסטרטגי מיידי.",
      formIntro: "רוצים קורס בהתאמה לארגון שלכם או באופן אישי? השאירו פרטים ונחזור אליכם.",
      typeLabel: "הקורס מיועד ל",
      typeOrg: "ארגון",
      typeIndividual: "פרטי",
      name: "שם מלא",
      namePlaceholder: "השם שלכם",
      email: "אימייל",
      emailPlaceholder: "you@company.com",
      phone: "טלפון",
      phonePlaceholder: "0500000000",
      note: "משהו שכדאי שנדע? (רשות)",
      notePlaceholder: "גודל צוות, מיקוד, תזמון.",
      submit: "להשארת פרטים",
      sending: "שולח…",
      ok: "תודה. הפרטים התקבלו, ונחזור אליכם בתוך יום עסקים אחד.",
      err: "משהו השתבש. נסו שוב, או כתבו ל-avraham@lalum.co.",
      need: "הזינו שם, אימייל תקין ומספר טלפון.",
    },
  },

  insights: {
    heroPill: "פתקי האלגוריסט",
    heroH1a: "על חשיבה משפטית,",
    heroH1b: "זיכרון של מכונה, והגנתיות.",
    heroLede: "הטור המתמשך שלנו על מה שנדרש כדי לבנות שיקול דעת שמחזיק מעמד מול בית המשפט.",
    ctaTitle: "החילו את אותה קפדנות על העניינים שלכם",
    ctaBody: "לקרוא זה טוב. ליישם על החשיפה שלכם זה טוב יותר. התחילו בפגישת אבחון Tech-Legal.",
  },

  legal: {
    eyebrow: "משפטי",
    title: "תנאים, פרטיות ונגישות",
    disclaimer: "עמוד זה הוא מידע כללי לאתר LALUM ואינו ייעוץ משפטי או הסכם מחייב. לייעוץ המותאם למצבכם, קבעו פגישת ייעוץ.",
    terms: {
      title: "תנאי שימוש",
      body: [
        "בשימוש באתר זה אתם מסכימים להשתמש בו כחוק ולא להסתמך על תוכנו כייעוץ משפטי. שום דבר כאן אינו יוצר יחסי עורך דין-לקוח; אלה מתחילים רק בהתקשרות חתומה.",
        "התוכן, המותג והחומרים באתר שייכים ל-LALUM ואין להעתיק או להפיץ אותם ללא רשות.",
      ],
    },
    privacy: {
      title: "פרטיות",
      body: [
        "אנחנו אוספים רק את מה שאתם שולחים לנו: הפרטים בבקשת פגישה או בהודעה, ולוגים טכניים בסיסיים הדרושים להפעלת האתר. אנחנו משתמשים בהם כדי לחזור אליכם ולהפעיל ולאבטח את השירות.",
        "אנחנו לא מוכרים את המידע שלכם. ענייני לקוח מוחזקים תחת חיסיון עורך דין-לקוח. תוכלו לשאול מה מוחזק אצלנו עליכם ולבקש תיקון או מחיקה.",
      ],
    },
    accessibility: {
      title: "הצהרת נגישות",
      body: [
        "LALUM מחויבת להנגיש את שירותיה הדיגיטליים לקהל הרחב ביותר האפשרי, לרבות אנשים עם מוגבלות, מתוך אמונה שלכל אדם זכות שווה לגלוש ברשת בכבוד ובעצמאות.",
        "אתר זה נבנה בהתאם לתקן הישראלי 5568 להנגשת תכנים באינטרנט ולהנחיות WCAG 2.1 ברמה AA, ובהתאם לתקנות שוויון זכויות לאנשים עם מוגבלות (התאמות נגישות לשירות), התשע\"ג 2013.",
        "בין אמצעי הנגישות באתר: מבנה כותרות ברור ועקבי, ניווט מלא במקלדת, סימון פוקוס נראה לעין בכל רכיב אינטראקטיבי, קישור דילוג לתוכן, ניגודיות צבעים מספקת, טקסט שנשאר קריא ומסתדר בנייד, תוויות מתארות לפקדים, ותמיכה בקוראי מסך בעברית ובאנגלית.",
        "חלק מהתכנים מסופקים באמצעות שירותי צד שלישי, כגון כלי תיאום הפגישות ופגישות הווידאו. אנו פועלים לשמור על שמישותם, אך רמת הנגישות שלהם נתונה בחלקה בידי הספק. אם נתקלתם בחסם ברכיב כזה, פנו אלינו ונסייע לכם ישירות.",
        "על אף מאמצינו, ייתכן שחלקים באתר עדיין אינם נגישים במלואם. אנו מתייחסים לכל פנייה בעדיפות וממשיכים לשפר.",
        "בקשות ופניות בנושא נגישות: אם נתקלתם בקושי, או שאתם זקוקים לתוכן בפורמט חלופי, פנו לרכז הנגישות שלנו בכתובת avraham@lalum.co. תארו את הבעיה, את העמוד, ואת הדפדפן או המכשיר שבו השתמשתם, ונחזור אליכם בתוך יום עסקים אחד.",
        "הצהרה זו נבדקה לאחרונה ביולי 2026.",
      ],
    },
    security: {
      title: "אבטחה",
      body: [
        "אנחנו מתייחסים ברצינות לאבטחת המידע של הלקוחות. הנתונים מועברים בחיבורים מוצפנים (HTTPS/TLS), ורשומות וקבצים של לקוחות נשמרים בתשתית מנוהלת עם בקרות גישה ואבטחה ברמת השורה, כך שכל לקוח מגיע רק לנתונים שלו.",
        "הגישה לאזור הלקוחות מחייבת אימות. מסמכים שאתם משתפים דרך הפורטל נשמרים במאגר פרטי שרק אתם והמשרד יכולים לפתוח. אנחנו מיישמים עקרון של הרשאות מינימום ושומרים על גישת ניהול מוגבלת למשרד בלבד.",
        "אף מערכת אינה מאובטחת לחלוטין. אם נתקלתם בפרצה או בחשש אבטחה, פנו אלינו בכתובת avraham@lalum.co ונטפל בכך במהירות.",
      ],
    },
    aiLiability: {
      title: "הגבלת אחריות ושימוש במערכות AI",
      body: [
        "החברה מבהירה בזאת כי חלק משירותי האתר, לרבות בוט עריכת והערכת ההסכמים, מופעלים ומבוססים על מערכות בינה מלאכותית (AI) ואלגוריתמים אוטומטיים. השירות ניתן כפי שהוא (AS-IS). החברה, מנהליה, עובדיה או מי מטעמה לא יישאו בכל אחריות שהיא, ישירה, עקיפה, תוצאתית או מיוחדת, בגין כל נזק, הפסד או עגמת נפש העלולים להיגרם למשתמש או לצד שלישי כתוצאה מהסתמכות על הפלטים, ההערות, הניתוחים או התוצאות המופקות על ידי הבוט.",
        "יודגש ומובהר כי פלטי הבוט אינם מחליפים ייעוץ משפטי מקצועי. אחריות משפטית וחובת זהירות מצד החברה תתגבש אך ורק בגין חוות דעת או ייעוץ משפטי פרטני, אשר ניתן באופן ישיר על ידי עורך דין מוסמך מטעם המשרד, בצורה כתובה, חתומה וכנגד תשלום שכר טרחה ייעודי.",
      ],
    },
  },

  data: {
    heroRows: [
      { icon: "shield", title: "הגנת IP ורישוי ל-AI", sub: "הגנה בת-הגנה על IP ועל קוד המקור", tag: "IP" },
      { icon: "settings", title: "צמיחת סטארטאפ וממשל חוזים", sub: "הסכמי מייסדים, חוזי טכנולוגיה וליווי סטארטאפים", tag: "LEGAL" },
      { icon: "scale", title: "רגולציה וציות ל-AI", sub: "ציות ל-EU AI Act וסיכון אלגוריתמי", tag: "REG" },
      { icon: "gavel", title: "גישור וייעוץ ניהולי (DOM)", sub: "ייעוץ אסטרטגי וגישור לסכסוכי נדל״ן וטכנולוגיה", tag: "DOM" },
    ],
    pillars: [
      { icon: "shield", tag: "IP ופרטיות", title: "ארכיטקטורה משפטית וקניין רוחני", body: "הגנה מוחלטת על ה-IP הארגוני. Privacy-by-Design מיושם בשלב הפיתוח, מניעת זיהום של קוד המקור, והתאמה מלאה למודלים מקומיים ולסביבות נתונים מוגנות." },
      { icon: "settings", tag: "ממשל ואוטומציה", title: "ממשל חוזים וסיכון אלגוריתמי", body: "הסכמי מייסדים, חוזי שותפים ועסקאות הפצה מורכבות מנוסחים בדיוק כירורגי. מערכות בקרה מונחות-נתונים שמביאות את החברה למצב של אפס חיכוך בכל עסקה." },
      { icon: "scale", tag: "צמיחה אסטרטגית", title: "כלכלה יישומית וייעוץ אסטרטגי", body: "בניית מודלים עסקיים היברידיים, ייעול עלויות תשתית ומחשוב, והכנה שיטתית של החברה לסבבי גיוס, בדיקת נאותות ועסקאות מסחריות בינלאומיות." },
    ],
    frameworks: [
      { code: "DEPLOY", title: "הטמעת AI מוגנת", icon: "brain", body: "אנחנו מקימים פלטפורמות AI בתוך הארגון שלכם על מודלים מקומיים ומערכות RAG, בגישת Privacy-by-Design: יכולת בלי דליפת IP או נתונים." },
      { code: "GOVERN", title: "ממשל מוטמע", icon: "shield", body: "ממשל חוזים מתמשך ומוכנות ל-EU AI Act מחווטים לתוך זרימת העבודה שלכם. החשיפה מזוהה וממותנת לפני שהיא הופכת לאחריות." },
      { code: "ENABLE", title: "הדרכה והכשרה", icon: "book", body: "הדרכה מקצועית להנהלה ולצוותי פיתוח, כדי שהאנשים שבונים ומכריעים יבינו את השטח המשפטי והקנייני שבו הם פועלים." },
    ],
    why: [
      { icon: "spark", title: "משרד ומעבדה", body: "ייעוץ משפטי מוביל ופרקטיקת פתרונות AI תחת קורת גג אחת, בלי מסירה, בלי אובדן בתרגום." },
      { icon: "scale", title: "דיוק אלגוריתמי", body: "הלוגיקה המשפטית גוברת על הסטטיסטיקה, לא להפך. המנוע מחזק את שיקול הדעת; לעולם אינו מחליף אותו." },
      { icon: "gavel", title: "בר-הגנה מעצם התכנון", body: "כל הכרעה ממוקרת, מתוארכת ובת-שחזור, בנויה להחזיק מעמד מול שופט." },
      { icon: "book", title: "20+ שנים, סיכון גבוה", body: "ניסיון עמוק במקום שבו החשיפה אמיתית: טכנולוגיה, נדל״ן וממשל מוסדי." },
    ],
    faqs: [
      { q: "מה מבדיל את המשרד שלכם ממשרדי טכנולוגיה מסורתיים?", a: "משרדים מסורתיים מייעצים על החוק בלי להבין שורת קוד אחת. אנחנו מגשרים על הפער הזה. כבוטיק Tech-Legal, אנחנו פועלים בצומת שבין משפט מתקדם, כלכלה יישומית וארכיטקטורת AI. אנחנו מבינים את המוצר, מערכות ה-RAG ומבני הנתונים שלכם מהיום הראשון, ומוודאים שהמסגרת המשפטית מגינה על הנכסים הטכנולוגיים שלכם ומחזקת אותם." },
      { q: "כיצד אתם מסייעים לסטארטאפים להגן על ה-IP בשימוש ב-AI יוצר?", a: "אנחנו מיישמים פרוטוקולים קפדניים של Privacy-by-Design. זה כולל הקמת סביבות מקומיות מאובטחות (בעזרת מודלים בקוד פתוח) כדי למנוע דליפת IP ונתוני לקוחות רגישים לעננים ציבוריים. אנחנו גם מעצבים מדיניות שימוש חזקה ב-AI כדי לוודא שהמפתחים לא יזהמו את קוד המקור הקנייני בחומר מוגן זכויות של צד שלישי, דבר שעלול לסכן גיוס עתידי או מיזוג ורכישה." },
      { q: "מהו מודל ה-Clinic and Engine?", a: "זו מסגרת תפעולית דו-כוחית. ה-Clinic מייצג את הידע, המחקר והייעוץ הבכיר שלנו, שם אנחנו מעבירים כיתות אמן, הכשרות להנהלה, ומנסחים אסטרטגיות משפטיות בהתאמה אישית. ה-Engine הוא זרוע הביצוע והאינטגרציה שלנו, שם אנחנו בונים פלטפורמות AI מאובטחות, מבצעים אוטומציה לממשל חוזים, ומהנדסים את התשתית ה-Tech-Legal בפועל עבור העסק שלכם." },
      { q: "כיצד מפגשי הייעוץ האסטרטגי שלכם מתייחסים לתחומים מסורתיים ומורכבים כמו נדל״ן לצד טכנולוגיה?", a: "אנחנו לא מתייחסים לטכנולוגיה ולנכסים פיזיים כאל עולמות נפרדים. מפגשי הייעוץ האסטרטגי שלנו מגשרים בין תחומים מסורתיים בעלי ערך גבוה, כמו עסקאות נדל״ן מורכבות, התחדשות עירונית (תמ״א 38), ומיסוי מקרקעין, לבין ארכיטקטורת tech-legal מתקדמת. תוך יישום המומחיות הכפולה שלנו ב-Law & Economics ובאוטומציה חוזית מתקדמת, אנחנו מבנים מחדש עסקאות נדל״ן בסיכון גבוה, מנהלים סכסוכי מיזמים משותפים, וממטבים תהליכי עסקה בדיוק מונחה-נתונים, ומגינים על הנכסים שלכם בעולם הפיזי והדיגיטלי כאחד." },
      { q: "מהו DOM (גישור מוכוון-הכרעה) וכיצד הוא פועל?", a: "DOM היא מסגרת קניינית בת 8 מודולים ליישוב סכסוכים, שתוכננה לסכסוכים מורכבים בנדל״ן, בתאגידים ובטכנולוגיה. בשונה מהתדיינות ממושכת או מגישור סטנדרטי, DOM תחומה בזמן, אנליטית ומובנית מאוד. היא משלבת משפט ומידול כלכלי כדי להוביל את הצדדים להסדר מיטבי ומחייב מבחינה משפטית, בלי לרוקן משאבים ארגוניים." },
      { q: "האם תוכלו לסייע לארגון שלנו לעמוד ברגולציית AI גלובלית כמו ה-EU AI Act?", a: "כן. אנחנו מתמחים בהנדסה רגולטורית יזומה. אנחנו מבצעים הערכות סיכון אלגוריתמיות ומיישרים את מערך הטכנולוגיה שלכם עם המסגרות הגלובליות המחמירות ביותר (כולל ה-EU AI Act ודיני פרטיות מתקדמים). אנחנו הופכים ציות ממכשול בירוקרטי ליתרון תחרותי שבונה אמון עם לקוחות ארגוניים." },
      { q: "האם אתם בונים בפועל את פלטפורמות ה-AI ואת זרימות העבודה האוטומטיות ללקוחות?", a: "בהחלט. אנחנו לא רק כותבים חוזים; אנחנו מהנדסים את המערכות שמנהלות אותם. אנחנו מסייעים לארגונים לבנות פלטפורמות AI פנימיות ומאובטחות, מסדי נתונים וקטוריים ייעודיים, וזרימות עבודה חוזיות אוטומטיות (Agentic Workflows) שמנהלות וממתנות סיכונים בזמן אמת באפס חיכוך." },
      { q: "מה כולל הליווי המשפטי המלא שלכם לסטארטאפים?", a: "אנחנו מספקים גיבוי משפטי וכלכלי מקצה לקצה מרגע ההקמה ועד לצמיחה. זה כולל בניית הסכמי מייסדים מתוחכמים, הקצאת IP, ממשל תאגידי, בניית מיזמים, וייצוג החברה בסבבי גיוס (SAFE, Equity) ובעסקאות מיזוג ורכישה אסטרטגיות." },
      { q: "מדוע פרספקטיבה כלכלית (Law & Economics) חיונית לעסק הטכנולוגי שלי?", a: "רגולציה טכנולוגית היא ביסודה כלכלית. תוך יישום עקרונות Law & Economics קפדניים, אנחנו לא רק בוחנים מה מותר מבחינה משפטית; אנחנו ממדלים את ההשפעה הפיננסית והתפעולית של מבנים משפטיים על העסק שלכם. כך הארכיטקטורה המשפטית תומכת בצמיחה בת-קיימא וממקסמת את שווי החברה." },
      { q: "כיצד עובדות ההדרכות וכיתות האמן הארגוניות שלכם?", a: "אנחנו מעבירים כיתות אמן וסדנאות ממוקדות ומעשיות לדירקטוריונים, לצוותי הנהלה ולמחלקות מו״פ. אנחנו מתרגמים מושגים tech-legal מורכבים, סיכונים אלגוריתמיים ורגולציה משתנה לכלי קבלת החלטות מעשיים ומוכווני-עסק." },
      { q: "כיצד מתחילים לעבוד אתכם?", a: "אנחנו מתחילים בפגישת אבחון Tech-Legal אסטרטגית. בפגישה ראשונית זו אנחנו ממפים את הארכיטקטורה הטכנית, המבנה התאגידי והחשיפה הרגולטורית הנוכחיים שלכם, כדי לזהות פגיעויות מיידיות ולתכנן מפת דרכים מותאמת למיזם שלכם." },
    ],
    advisoryServices: [
      { icon: "shield", title: "הגנת קניין רוחני", body: "בניית שכבת IP בת-הגנה סביב הטכנולוגיה שלכם: פטנטים, סודות מסחריים ומודלים קנייניים, המהונדסים כיתרון תחרותי שעומד במבחן משקיע ובית משפט." },
      { icon: "settings", title: "ממשל חוזים אוטומטי", body: "מסגרות סטנדרטיות, בקרה לאורך מחזור החיים, וניטור כדי שכל הסכם יישאר עקבי, עדכני ואכיף, באפס חיכוך בכל עסקה." },
      { icon: "scale", title: "ניהול סיכוני רגולציה", body: "מיפוי וניהול חשיפה רגולטורית מתקדמת, לרבות ה-EU AI Act, משלב הפיתוח, כדי למנוע חשיפה משפטית וכלכלית קריטית בטרם תיווצר." },
      { icon: "brain", title: "ארכיטקטורת נתונים מאובטחת", body: "ליווי בארכיטקטורת מודלים מקומיים ו-RAG בגישת Privacy-by-Design: פרטיות ואבטחה מובנות בבסיס, לא מוצמדות בדיעבד." },
      { icon: "file", title: "ליווי מיזמים וסטארטאפים", body: "מעטפת אסטרטגית לחברות טכנולוגיה ולפרטים: התאגדות, סבבי גיוס, הסכמי מייסדים ועובדים, וליווי שוטף בעידן ה-AI." },
      { icon: "search", title: "בדיקת נאותות טכנולוגית", body: "בדיקת נאותות משפטית וטכנית לעסקאות ולגיוסים: זיהוי חשיפה ב-IP, בנתונים וברגולציה לפני שהיא הופכת לעלות." },
    ],
    domModules: [
      { icon: "scale", title: "תהליך מובנה ותחום בזמן", body: "מסגרת בת 8 מודולים שמחליפה התדיינות ממושכת במסלול אנליטי ותחום בזמן להכרעה." },
      { icon: "brain", title: "מידול משפטי וכלכלי", body: "כל עמדה ממודלת דרך הדוקטרינה המשפטית וההשפעה הכלכלית כאחד, ומובילה את הצדדים להסדר מיטבי ומחייב." },
      { icon: "shield", title: "תוצאה מחייבת ובת-הגנה", body: "הסדר מחייב מבחינה משפטית ובנוי על תיעוד בר-הגנה, בלי לרוקן משאבים ארגוניים." },
    ],
    testimonials: [
      { quote: "LALUM בנו מחדש את כל מסגרת ממשל החוזים שלנו. המהירות והמבנה שינו את אופן הפעולה של הארגון כולו.", attr: "סמנכ״ל כספים, תאגיד כלכלי עירוני" },
      { quote: "הם מבינים סיכון בבנייה כמו שהמהנדסים שלנו מבינים קיר נושא, ומגבים זאת בקפדנות אלגוריתמית.", attr: "יועץ משפטי, קבוצת תשתיות" },
      { quote: "מודל הסיכון סימן חשיפה שהיועצים הקודמים שלנו פספסו במשך שנים. כך נראה דיוק אלגוריתמי הלכה למעשה.", attr: "מנכ״ל, יזם נדל״ן" },
    ],
    plans: [
      { name: "מנדט בהיקף קבוע", tagline: "התקשרות מוגדרת, עלות צפויה", best: "מתאים ל: עניין יחיד בסיכון גבוה עם תוצר ברור", popular: false, features: ["זמן תגובה עד שעה", "הערכת סיכונים אלגוריתמית", "תוצר מוכן לבית המשפט", "מחיר קבוע, ללא חיוב שעתי"], cta: "לבקשת הצעת היקף" },
      { name: "שותפות ריטיינר", tagline: "צוות המשפט וה-AI המשובץ שלכם", best: "מתאים ל: ארגונים צומחים עם חשיפה מתמשכת", popular: true, features: ["מענה בעדיפות עד שעה", "עורך דין ייעודי", "ניטור סיכונים רציף (RECIR)", "ייעוץ ללא הגבלה"], cta: "לתיאום פגישת ייעוץ" },
    ],
    audiences: [
      { icon: "spark", title: "הנהלה ומנהלים בכירים", body: "שכבת שיקול הדעת. מספיק שליטה כדי להוביל יוזמות AI, לקרוא את הסיכון, ולשאול את השאלות הנכונות לפני אישור.", points: ["היכן AI יוצר חשיפה משפטית וקניינית", "חובות ה-EU AI Act ברמת הדירקטוריון", "הכרעות ממשל שבאחריותכם"] },
      { icon: "brain", title: "צוותי פיתוח ומוצר", body: "שכבת הבנייה. פרקטיקות קונקרטיות כדי שמה שמשוגר יהיה תואם, נקי מבחינת IP ובר-הגנה מה-commit הראשון.", points: ["Privacy-by-Design בתוך ה-pipeline", "הימנעות מזיהום קוד מקור ונתונים", "מודלים מקומיים ו-RAG בבטחה"] },
    ],
    trainingModules: [
      { icon: "shield", title: "יסודות סיכון AI ו-IP", body: "הנוף המרכזי: היכן ממוקמים בפועל הקניין הרוחני, הנתונים והאחריות במוצר AI." },
      { icon: "scale", title: "EU AI Act הלכה למעשה", body: "סיווג סיכון, חובות ותיעוד, מתורגמים מרגולציה למשימות הנדסה." },
      { icon: "file", title: "ממשל חוזים ונתונים", body: "מה שההסכמים וזרימות הנתונים שלכם חייבים לכסות כאשר AI בתמונה, ואיך לשמור עליהם אכיפים." },
      { icon: "brain", title: "דפוסי ארכיטקטורה מאובטחת", body: "Privacy-by-Design, מודלים מקומיים ו-RAG: הדפוסים ששומרים על היכולת בלי לדלוף IP או נתונים." },
      { icon: "search", title: "לקרוא את החשיפה", body: "איך לזהות חשיפה משפטית וכלכלית מוקדם: רשימת בדיקה משותפת לסקירות מוצר ולהכרעות go/no-go." },
      { icon: "gavel", title: "מאירוע להגנה", body: "מה המשמעות של בר-הגנה בפועל: מיקור, תיארוך, והתיעוד שעומד בביקורת." },
    ],
    formats: [
      { meta: "חצי יום", title: "תדריך להנהלה", body: "מפגש חד להנהלה: תמונת הסיכון וההכרעות שבאחריותם." },
      { meta: "4 עד 6 שבועות", title: "תוכנית צוותית", body: "מסלול מובנה לצוותי פיתוח ומוצר, מיושם על הסטאק שלכם." },
      { meta: "מתמשך", title: "יועץ מוטמע", body: "מפגשים חוזרים ושעות פתוחות ככל שהמוצר והרגולציה מתפתחים." },
    ],
    articles: [
      {
        slug: "legal-logic", icon: "scale", category: "דוקטרינה",
        title: "מדוע הלוגיקה המשפטית חייבת לגבור על הסטטיסטיקה",
        dek: "מודל שמנבא שפה אינו מודל שחושב על משפט. הפער בין השניים הוא המקום שבו תיקים נקבעים.",
        date: "יולי 2026", read: "6 דקות קריאה",
        blocks: [
          { type: "p", text: "מודל שפה גדול הוא, בבסיסו, מכשיר מתאם יוצא דופן. הוא קרא יותר חוזים, פסקי דין וחוקים מכל אדם, והוא מנבא בשטף מדהים איך משפט משפטי נוטה להיראות. השטף הזה מפתה, ובדיוק לכן הוא מסוכן כשמניחים לו להריץ חשיבה משפטית ללא פיקוח." },
          { type: "p", text: "הסכנה אינה שהמכונה תחשוב כמו אדם. הסכנה היא שאדם יתחיל לחשוב כמו המכונה, ויבלבל בין מה שנפוץ סטטיסטית לבין מה שנכון משפטית. הסעיף השכיח ביותר אינו הבר-הגנה ביותר. התשובה הסבירה ביותר אינה זו שבית משפט יקבל." },
          { type: "quote", text: "הלוגיקה המשפטית גוברת על הסטטיסטיקה, לעולם לא להפך." },
          { type: "h2", text: "היכן המתאם נשבר" },
          { type: "p", text: "קחו סעיף שיפוי שמופיע בתשעים אחוז מהסכמי הספקים. מודל סטטיסטי ישחזר אותו בשמחה, כי הוא נפוץ. אבל שכיחות אינה אומרת דבר על אכיפות בתחום השיפוט שלכם, תחת הדין החל עליכם, כנגד הצד הספציפי שלכם. הדוקטרינה, שרשרת ההיגיון המשפטי עצמה, סמויה ממערכת שמודדת רק תדירות." },
          { type: "p", text: "זהו כשל שאנחנו מהנדסים כנגדו. כל תוצר שיוצא מ-LALUM עובר דרך שכבה דוקטרינרית לפני שהוא נחשב מוגמר:" },
          { type: "list", items: ["הטיוטה הסטטיסטית נוצרת ומטופלת כהשערה, לא כתשובה.", "ההשערה נחקרת נגדית מול הדוקטרינה, החקיקה והתקדים המחייב הנוכחיים.", "מה ששורד ממוקר ומתוארך; מה שאי אפשר להגן עליו נפסל."] },
          { type: "h2", text: "שיקול הדעת הוא המוצר" },
          { type: "p", text: "האוטומציה אמיתית ורבת עוצמה, אך היא קיימת כדי לפנות את השולחן, לא כדי לקבל את ההכרעה. מה שנותר לאחר סילוק העבודה החוזרת הוא החלק שתמיד היה חשוב: שיקול דעת, אסטרטגיה, והנכונות לשאת באחריות לעמדה. זו עבודת עורך דין, וזו העבודה שאנחנו מגינים עליה." },
          { type: "p", text: "אלגוריתם יכול לומר לכם מה סביר. רק לוגיקה משפטית יכולה לומר לכם מה נכון, ורק עורך דין מוסמך יכול לחתום על כך בשמו." },
        ],
      },
      {
        slug: "memory", icon: "brain", category: "ארכיטקטורה",
        title: "זיכרון לטווח ארוך: לתת ל-AI המשפטי היסטוריית תיקים",
        dek: "רוב הכלים המשפטיים שוכחים ברגע שסוגרים את הלשונית. הידע המשפטי של ארגון ראוי ליותר משִׁכחה.",
        date: "יוני 2026", read: "8 דקות קריאה",
        blocks: [
          { type: "p", text: "שאלו עוזר משפטי גנרי את אותה שאלה פעמיים, והוא יענה כזר בשתי הפעמים. אין לו זיכרון של העניינים הקודמים שלכם, אין לו תחושה של עמדת הסיכון שלכם, אין לו תיעוד של הפשרה שהגעתם אליה ברבעון שעבר ולמה. כל אינטראקציה מתחילה מאפס. לשאלות מזדמנות זה בסדר. לארגון שנושא חשיפה אמיתית, זו חולשה מבנית." },
          { type: "p", text: "הערך של יועץ פנימי מצוין אינו שהוא עונה מהר, אלא שהוא זוכר. הוא יודע איזה ספק תמיד דוחף לאחריות בלתי מוגבלת, איזה סעיף הדירקטוריון שלכם לעולם לא יאשר, איזה סכסוך עבר עדיין מעצב את אופן ההתקשרות שלכם. הזיכרון המוסדי הזה הוא הנכס. הוא גם בדיוק מה שרוב ה-AI המשפטי זורק." },
          { type: "h2", text: "המודל התפעולי העמוק" },
          { type: "p", text: "מסגרת ה-DOM של LALUM נבנתה כדי להחזיק את הזיכרון הזה. במקום להתייחס למסמכים שלכם כערימת קבצים לחיפוש, היא ממדלת את המציאות המשפטית שלכם כמערכת חיה, כל חוזה, התחייבות ותלות מיוצגים כצומת שניתן לתשאל, לנטר ולנתח לאורך זמן." },
          { type: "quote", text: "אנחנו לא שואלים שאלות של זר. אנחנו נותנים למערכת זיכרון שמשתפר עם כל קובץ חדש." },
          { type: "p", text: "מכיוון שהמודל מתמיד, הוא מצטבר. כל עניין חדש לא רק נפתר, אלא הופך את הבא אחריו לחד יותר:" },
          { type: "list", items: ["תקדים מהעסקאות הקודמות שלכם מזין טיוטות חדשות, לא רק הקורפוס הציבורי.", "צדדים חוזרים והדפוסים שלהם נזכרים לרוחב העניינים.", "עמדה שננקטה בחוזה אחד נבדקת לעקביות מול כל האחרים."] },
          { type: "h2", text: "זיכרון שבבעלותכם" },
          { type: "p", text: "הזיכרון הזה שלכם בלבד. היסטוריית התיקים שלכם מאמנת את המודל שלכם, היא לעולם אינה מאוגמת עם לקוחות אחרים או נחשפת אליהם. סודיות כאן אינה הגדרה שמפעילים; היא חובה מקצועית שקדמה לטכנולוגיה במאות שנים." },
          { type: "p", text: "התוצאה היא ליווי משפטי שעושה את מה שיועץ מהימן עושה: הוא זוכר, הוא משתפר, והוא הופך יקר ערך יותר ככל שעובדים אתו זמן רב יותר." },
        ],
      },
      {
        slug: "defensible", icon: "shield", category: "פרקטיקה",
        title: "בר-הגנה מעצם התכנון: מה ששורד חקירה נגדית",
        dek: "יש הבדל בין תשובה שאפשר לפעול לפיה לבין תשובה שאפשר להגן עליה מול שופט. אנחנו בונים לשנייה.",
        date: "יוני 2026", read: "5 דקות קריאה",
        blocks: [
          { type: "p", text: "מהירות קל להדגים וקל למכור. הגנתיות אינה כזו, ובדיוק לכן היא התכונה החשובה ביותר. תשובה מהירה שקורסת תחת ביקורת גרועה מאין תשובה כלל, כי כבר הסתמכו עליה עד שהיא נכשלת." },
          { type: "p", text: "לכן אנחנו שואלים שאלה קשה יותר על כל תוצר לפני שהוא יוצא מאתנו: האם זה ישרוד חקירה נגדית? לא האם זה סביר, לא האם זה נשמע נכון, אלא האם עורך דין מוסמך יכול לעמוד מאחוריו, תחת אתגר, מול בית משפט?" },
          { type: "h2", text: "שלוש תכונות" },
          { type: "p", text: "לתוצר בר-הגנה יש שלוש תכונות, ומסגרת ה-SRME אוכפת את שלושתן לפני החתימה:" },
          { type: "list", items: ["ממוקר: כל עמדה מתחקה אל הסמכות שעליה היא נשענת, לא אל ניחוש בטוח.", "מתוארך: הוא נוקב בגרסת החוק שעליה הסתמך, כדי שניתן יהיה לבחון אותו מול החוק כפי שהיה.", "בר-שחזור: אותם קלטים מפיקים את אותו היגיון, מילה במילה, בכל פעם."] },
          { type: "quote", text: "מה שאי אפשר להגן עליו מול שופט לעולם אינו מופיע בתוצר." },
          { type: "h2", text: "החתימה האנושית" },
          { type: "p", text: "הטכנולוגיה מביאה אותנו לטיוטה בת-הגנה במהירות. היא אינה מדלגת על הצעד האחרון. כל תוצר נבדק ונחתם בידי עורך דין מוסמך שאחראי לו אישית. ה-AI מסייע; עורך הדין מכריע. החתימה הזו אינה פורמליות, היא כל העיקר." },
          { type: "p", text: "הגנתיות, בסופו של דבר, אינה תכונה שמוסיפים בסוף. היא משמעת שמתכננים לתוך העבודה מהשורה הראשונה, ואז מסרבים להתפשר עליה." },
        ],
      },
    ],
  },
};

export const strings: Record<"en" | "he", Dict> = { en, he };
